adj1=input("Enter an adjective:")
noun1=input("Enter an animal name:")
adj2=input("Enter adjective describing the animal:")
verb=input("Enter the action doing by the animal:")
noun2=input("Enter some food:")
print(f"Today I went to a {adj1} zoo park.")
print(f"There I saw a {noun1}.")
print(f"It looks so {adj2} and it was {verb}.")
print(f"Before leaving we bought some {noun2} to feed the {noun1}.")